### ISSUE TITLE
Automatic changes to .gitlab-ci.yml quote _everything_

### ISSUE THREAD

**Issue by samba** [failfast-ci/failfast-api#16]
The YAML format produced by the automatic changes `.gitlab-ci.yml` includes full quotation of all attributes. This reduces readability for users who review the file within GitLab.

Preferred behavior:

- Only modify specific parts of the file which require updates.
- Avoid quoting properties (names or values) if not required, to allow syntax highlighters to present the file more readably.

**Comment by samba** [comment]
We're happy to address this [downstream][1] and file a PR accordingly :)

[1]: https://github.com/samsung-cnct/failfast-api

**Comment by ant31** [comment]
The automatic changes are a workaround to add a job that trigger statuses. 
I would prefer to implement gitlab hooks:  #7  and remove the generation of a new .gitlab-ci.yml

"gitlab job status is updated" -> callback -> "failfast-api" -> "update github status"

**Comment by ant31** [comment]
As quick fix should be easy to remove at least quotes, I'll do it. 

Do you plan to help on #7 ?

**Comment by samba** [comment]
We're definitely interested to help. Currently building out a GitLab deployment for our org, improving this integration is valuable for us, but a matter of timing. :) 

Further discussion in comments of #7 then?
